# Generated by Django 4.2.2 on 2023-10-31 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0009_cercado_name_alter_gpsdevice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsdevice',
            name='cercado',
        ),
    ]
