# Generated by Django 4.2.2 on 2023-11-01 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0010_remove_gpsdevice_cercado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevice',
            name='cercado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gps_app.cercado'),
        ),
    ]
