# Generated by Django 4.2.2 on 2023-11-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0011_gpsdevice_cercado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cercado',
            name='lat1',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cercado',
            name='lat2',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cercado',
            name='lat3',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cercado',
            name='lat4',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cercado',
            name='lon1',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cercado',
            name='lon2',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cercado',
            name='lon3',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cercado',
            name='lon4',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
